language: ru_RU
#########################################################################
#                       Конфигурация БД                                 #
#########################################################################
MySQL:
  Enable: false                  #если false, будет юзаться SQLite
  Database: "DraimLogin"
  Username: "DraimLogin"
  Password: "OftenGAY"
  Host: "localhost"
  Port: 3306
  SSL: false

bungee: false   #Включите, если вы работаете c связкой серверов (помните, что этот плагин также следует разместить в плагинах bungeecord)

#########################################################################
#                       Конфигурация Бота                               #
#########################################################################
bot:
  name: "@НикБота"
  token: "ТвойТокен"    #Можно найти у @BotFather

#########################################################################
#                            Сессии                                     #
#########################################################################

login-session: true     #если true, не нужно повторять проверку в telegram при каждом входе на сервер
#если false, нужно повторять проверку в telegram при каждом входе на сервер


#########################################################################
#                                2FA                                    #
#########################################################################
2FA:
  enabled: false  #если false, плагин будет использоваться в качестве основной системы входа в систему (отключение всех команд)
  #если true, то разрешается онли команды из "allowedCommands"
  allowed-commands:
    - "/login"
    - "/register"
